---
services:
  panel:
    image: ghcr.io/pterodactyl/panel:v1.11.0
    container_name: panel
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "redis"
      APP_URL: http://10.10.0.12:80
      DB_HOST: mysql
      DB_DATABASE: ${mysql_database}
      DB_USERNAME: ${mysql_user}
      DB_PASSWORD: ${mysql_user_password}
      DB_PORT: 3306
      APP_TIMEZONE: Europe/Oslo
    depends_on:
      - mysql
    volumes:
      - "./data/var/:/app/var/"
      - "./data/nginx/:/etc/nginx/http.d/"
      - "./data/certs/:/etc/letsencrypt/"
      - "./data/logs/:/app/storage/logs"
    networks:
      - panel
      
  mysql:
    container_name: mysql
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
      MYSQL_DATABASE: ${mysql_database}
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_user_password}
    volumes:
      - ./data/db:/var/lib/lysql
    networks:
      - panel

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    networks:
      - panel

networks:
  panel:
