---
services:
  panel:
    image: ghcr.io/pterodactyl/panel:v1.11.0
    container_name: panel
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      APP_URL: ${app_url}

      DB_HOST: mysql
      DB_DATABASE: ${mysql_database}
      DB_USERNAME: ${mysql_user}
      DB_PASSWORD: ${mysql_user_password}
      DB_PORT: 3306
      APP_TIMEZONE: Europe/Oslo

      CACHE_DRIVER: "redis"
      SESSION_DRIVER: "redis"
      QUEUE_DRIVER: "redis"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ${redis_password}
    depends_on:
      - mysql
    volumes:
      - "./data/var/:/app/var/"
      - "./data/nginx/:/etc/nginx/http.d/"
      - "./data/certs/:/etc/letsencrypt/"
      - "./data/logs/:/app/storage/logs"
    networks:
      - panel
      
  mysql:
    image: mariadb:11.6.2
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
      MYSQL_DATABASE: ${mysql_database}
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_user_password}
    volumes:
      - ./data/db:/var/lib/lysql
    networks:
      - panel

  redis:
    image: redis:7.4.2
    container_name: redis
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$${redis_password:?redis_password variable is not set}"
    env_file:
      - .env
    volumes:
      - ./data/reedis:/var/lib/redis/data
      - ./data/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - panel

networks:
  panel: