version: '3.3'
services:
  mongodb:
    image: mongodb/mongodb-community-server
    restart: always
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - ./db_data:/data
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=
      - ME_CONFIG_MONGODB_ADMINPASSWORD=
    networks:
      - db
networks:
  db: