services:
  db:
    container_name: efscalculator-db
    image: mongo:8.0.6
    restart: unless-stopped
    ports:
      - 27017:27017
    env_file: 
      - .env
    volumes:
      - ./db:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js