version: '3.3'

services:
  portainer: 
      image: portainer/portainer-ce:latest 
      restart: unless-stopped  
      container_name: portainer
      volumes:
        - ./data:/data
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - '8000:9443'
