version: '3.9'
services:
  iventoy:
    image: ziggyds/iventoy:latest
    container_name: iventoy
    restart: always
    privileged: true #must be true
    ports:
      - 26000:26000
      - 16000:16000
      - 10809:10809
      - 67:67/udp
      - 69:69/udp
    volumes:
      - isos:/app/iso
      - config:/app/data
      - /<path to logs>:/app/log
    environment:
      - AUTO_START_PXE=true # optional, true by default


# required or no workey for config
volumes:
  isos:
    external: true
  config:
    external: true