version: '3.8'

services:
  onlyoffice-mysql-server:
    image: mysql:latest
    container_name: onlyoffice-mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: onlyoffice
    volumes:
      - /app/onlyoffice/CommunityServer/mysql:/var/lib/mysql

  onlyoffice-document-server:
    image: onlyoffice/documentserver-de
    container_name: onlyoffice-document-server
    restart: always
    environment:
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data

  onlyoffice-mail-server:
    image: onlyoffice/mailserver
    container_name: onlyoffice-mail-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: onlyoffice_mailserver
    volumes:
      - /app/onlyoffice/CommunityServer/mail:/var/vmail
      - /app/onlyoffice/CommunityServer/mail/config:/etc/postfix
      - /app/onlyoffice/CommunityServer/mail/logs:/var/log/mail

  onlyoffice-control-panel:
    image: onlyoffice/controlpanel
    container_name: onlyoffice-control-panel
    restart: always

  onlyoffice-community-server:
    image: onlyoffice/communityserver
    container_name: onlyoffice-community-server
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "5222:5222"
    environment:
      MYSQL_SERVER_HOST: onlyoffice-mysql-server
      MYSQL_SERVER_USER: onlyoffice_user
      MYSQL_SERVER_PASS: onlyoffice_pass
      DOCUMENT_SERVER_PORT_80_TCP_ADDR: onlyoffice-document-server
      DOCUMENT_SERVER_JWT_ENABLED: "true"
      DOCUMENT_SERVER_JWT_SECRET: ${JWT_SECRET}
      DOCUMENT_SERVER_JWT_HEADER: AuthorizationJwt
      MAIL_SERVER_API_HOST: ${MAIL_SERVER_IP}
      MAIL_SERVER_DB_HOST: onlyoffice-mysql-server
      MAIL_SERVER_DB_NAME: onlyoffice_mailserver
      MAIL_SERVER_DB_PORT: 3306
      MAIL_SERVER_DB_USER: root
      MAIL_SERVER_DB_PASS: my-secret-pw
      CONTROL_PANEL_PORT_80_TCP: 80
      CONTROL_PANEL_PORT_80_TCP_ADDR: onlyoffice-control-panel
    volumes:
      - /app/onlyoffice/CommunityServer/data:/var/www/onlyoffice/Data
      - /app/onlyoffice/CommunityServer/logs:/var/log/onlyoffice
      - /app/onlyoffice/CommunityServer/letsencrypt:/etc/letsencrypt
    privileged: true
    cgroupns_mode: host
