version: '3.3'

services:
  uptime-kuma: 
      image: louislam/uptime-kuma:latest
      restart: always  
      container_name: kuma
      volumes:
        - ./data:/app/data
      ports:
        - '8020:3001'
