services:
  frontend: 
    image: node:latest
    restart: unless-stopped  
    container_name: app
    volumes:
      - /data:/data
    ports:
      - '3000:3000'
    build:
      context: ./
      dockerfile: Dockerfile
