version: '3.3'
services:
  trilium:
    image: zadam/trilium:latest 
    restart: always 
    container_name: trilium-demo 
    volumes:
      - DATA:/home/node/trilium-data 
    ports: 
      - '8010:8080'
volumes:
  DATA: